version: '3'
services:
    db:
        image: postgres:12.4
        environment:
            POSTGRES_PASSWORD: enviu_dev
            POSTGRES_USER: postgres
    blockscout:
        image: surfingnerd/blockscout-dmd:v0.9-411
        depends_on:
            - "db"
        ports:
            - "4000:4000"
        tty: true
        environment:
            ETHEREUM_JSONRPC_HTTP_URL: http://185.187.170.209:38000
            ETHEREUM_JSONRPC_TRACE_URL: http://185.187.170.209:38000
            ETHEREUM_JSONRPC_WS_URL: ws://185.187.170.209:38001
            ETHEREUM_JSONRPC_VARIANT: parity
            HOST: 127.17.0.1
            DATABASE_URL: postgresql://postgres:enviu_dev@db:5432/explorer?ssl=false
            COIN: ""
            SHOW_ADDRESS_MARKETCAP_PERCENTAGE: "false"
            DISABLE_EXCHANGE_RATES: "true"
            SHOW_PRICE_CHART: "false"
            CHAIN_SPEC_PATH: "https://raw.githubusercontent.com/DMDcoin/dmdv4-testnet/alpha3/spec.json"
