version: '3'
services:
    db:
        image: postgres:12.5
        environment:
            POSTGRES_PASSWORD: enviu_dev
            POSTGRES_USER: postgres
        network_mode: host
    blockscout:
        image: surfingnerd/blockscout-dmd:v0.9-411
        depends_on:
            - "db"
        tty: true
        network_mode: host
        environment:
            ETHEREUM_JSONRPC_HTTP_URL: http://127.0.0.1:8540
            ETHEREUM_JSONRPC_TRACE_URL: http://127.0.0.1:8540
            ETHEREUM_JSONRPC_WS_URL: ws://127.0.0.1:9540
            ETHEREUM_JSONRPC_VARIANT: parity
            HOST: 127.17.0.1
            DATABASE_URL: postgresql://postgres:enviu_dev@127.17.0.1:5432/explorer?ssl=false
            COIN: "DMD"
            SHOW_ADDRESS_MARKETCAP_PERCENTAGE: "false"
            DISABLE_EXCHANGE_RATES: "true"
            SHOW_PRICE_CHART: "false"
            LINK_TO_OTHER_EXPLORERS: "false"