

version: '3.8'
services:
  db:
    #image: postgres:15.3
    build: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DMD_DB_POSTGRES}
    ports:
      - '5432:5432'
#    volumes: 
#      - db:/var/lib/postgresql/data
#volumes:
#  db:
#    driver: local