version: '3.8'
networks:
  monitor-net:
    driver: bridge
services:
  db:
    #image: postgres:15.3
    build: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DMD_DB_POSTGRES}
    ports:
      - '5432:5432'
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    # volumes:
    #   - ./grafana/etc:/etc/grafana/
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"